### PR TITLE
change backup restart policy to never

### PR DESCRIPTION
**Pull request by philbrookes**
## Motivation
INTLY-3842

### CODE REVIEW

**Comment by davidffrench** [comment]
code changes look perfect @philbrookes . Have you verified this based on Robs steps to reproduce in the JIRA?

**Comment by philbrookes** [comment]
not yet, I have no cluster to test on at the moment, once I do, I will.

**Comment by philbrookes** [comment]
Here's how I've been trying to verify this:
- created an RHPDS integreatly cluster (manifest suggests it is running 1.5.1)
- created a backup entry in the keycloak CR
- it was set to restart on failure
- created the job (from the created cronjob template) and it never failed, there was no entries in alertmanger
- changed the keycloak-operator image to an image that includes this change
- created the job (from the created cronjob template) and it failed
- there was no entries in alertmanger (maybe I need to install some kind of montoring or something, to see this?)

**Comment by davidffrench** [comment]
@obrienrobert should be able to help verify this one. What cluster were you using where you saw this error and can you verify it there?

**Comment by philbrookes** [comment]
it turns out the new alert rules for capturing this are not installed as part of release-1.5.1, testing them manually shows this alerting is functional. So this PR is now verified.

**Pull request merged**
