### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by aidenkeating**
Bump version to `1.1.0`

### CODE REVIEW

**Comment by aidenkeating** [comment]
@pb82 Mind taking a look?

**Comment by pb82** [comment]
:eyes:

**Comment by pb82** [comment]
minor nit-pick: it still says 0.0.5 here: https://github.com/integr8ly/keycloak-operator#test-it-locally

**Comment by aidenkeating** [comment]
@pb82 That looks to be referring to the version of the Operator Framework printed during a run. I've updated it to be the `0.0.7` release which is what I've been using with this operator.

I don't seem to be able to merge on this repo, mind merging?

**Comment by pb82** [comment]
@aidenkeating merged

**Pull request merged**
