### PR TITLE
Add linkOnly and authenticateByDefault property to kc idp typ

### PR DESCRIPTION
**Pull request by JameelB**
## Motivation
This is required for creating a [Github](https://github.com/integr8ly/integreatly-operator/pull/61/files#diff-329c149b9583e9a4fcdb670a2ba866f0R316-R317) identity provider to be used for Launcher & Che in OpenShift 4.

## What
This adds the properties `linkOnly` to the [Keycloak Identity Provider](https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_identityproviderrepresentation) type.

## Why
The Github identity provider created for Launcher and Che in OpenShift 4 requires the `Account Linking Only` to be set to true.

## Verification Steps
1. Run the operator
2. Create a Keycloak realm that has an identity provider with `LinkOnly` set to true.
  - **Verify**: Identity provider should have been created successfully
  - **Verify**: The property `Account Linking Only` of that identity provider should be set to true

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Additional Notes
Related PR: https://github.com/integr8ly/integreatly-operator/pull/61

### CODE REVIEW

**Comment by matskiv** [comment]
@JameelB Hmm, I don't see `authenticateByDefault` in KeyCloak API docs.

**Comment by JameelB** [comment]
@matskiv Hmm, thought it would be there. That was from the exported identity provider config: 
```{
      "alias": "",
      "displayName": "",
      "internalId": "",
      "providerId": "",
      "enabled": true,
      "updateProfileFirstLoginMode": "",
      "trustEmail": false,
      "storeToken": true,
      "addReadTokenRoleOnCreate": true,
      "authenticateByDefault": false,
      "linkOnly": false,
      "firstBrokerLoginFlowAlias": "first broker login",
      "config": {
        "hideOnLoginPage": "true",
        "clientId": "",
        "disableUserInfo": "",
        "clientSecret": "",
        "defaultScope": "",
        "useJwksUrl": "true"
      }
    }```

Can delete that here, it doesn't seem to be required. :+1:

**Comment by matskiv** [comment]
@JameelB yeah, let's delete it, just to keep our code consistent with the API :)

**Comment by matskiv** [comment]
Don't forgett tto create a GitHub release once you merge ;)

**Pull request merged**
