### PR TITLE
updated probes configuration

### PR DESCRIPTION
**Pull request by jhellar**
## Motivation

Match probes config with RHMI 2 keycloak.

https://issues.redhat.com/browse/INTLY-9471

## Verification Steps

1. Create PDS cluster
2. Build operator image
    1. Clone `keycloak-operator` repo locally in `$GOPATH/src/github.com/integr8ly/keycloak-operator`
    2. Fetch and checkout this PR
    3. Download it from https://github.com/operator-framework/operator-sdk/releases/tag/v0.8.1
    4. Copy it to `~/bin/operator-sdk`
    5. Edit `Makefile`
    6. Change `OPERATOR_SDK_BINARY` to point to your operator-sdk v0.8.1 binary
    7. Edit `Makefile`
    8. Change `ORG` to your quay.io org
    9. `ln -s ./tmp/build build`
    10. `docker login quay.io` with your account
    11. `make image/build`
    12. `make image/push`
    13. Make the image public in quay.io
3. ssh to your PDS
4. `oc new-project test`
5. `git clone https://github.com/integr8ly/keycloak-operator.git`
6. Edit image in `deploy/operator.yaml` to point to your quay.io org
7. `kubectl apply -f deploy/crds/Keycloak_crd.yaml`
8. `kubectl apply -f deploy/crds/KeycloakRealm_crd.yaml`
9. `kubectl apply -f deploy/rbac.yaml -n test`
10. `kubectl apply -f deploy/operator.yaml -n test`
11. `kubectl apply -f deploy/examples/keycloak.json`
12. `oc get dc sso -o yaml`
13. Check probes config - changes to probes in this PR should be there

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress

- [x] Finished task
- [ ] TODO

### CODE REVIEW

**Comment by philbrookes** [comment]
I was under the impression we are no longer using our fork for 2.x?

**Comment by jhellar** [comment]
@philbrookes thanks for review. This is for RHMI 1.x, to make sure that probes configuration is the same as in RHMI 2.x.

**Comment by jessesarn** [comment]
@philbrookes doesn't look like it automerges.. I don't want to override without knowing the impact.  Can you make sure this is merged if its ok?

**Pull request merged**
