### PR TITLE
INTLY-1201 use master image tag in master branch

### PR DESCRIPTION
**Pull request by tremes**
See https://issues.jboss.org/browse/INTLY-1201. We want to be sure we test the latest stuff and thus we think there should be a master image tag in the master branch.

### CODE REVIEW

**Comment by trepel** [comment]
I would like to get an agreement on what tag the master branch should point to. Is there any reason why the 'master' branch should point to a specific tag in quay.io or is it ok to change it to 'master' tag?

@aidenkeating @philbrookes @david-martin @maleck13 @mikenairn (sorry for the wide audience, not sure who might have a strong opinion on this)

**Comment by trepel** [comment]
It seems @maleck13 agrees with this but the release pipeline needs to be adjusted. See a small conversation here: https://github.com/integr8ly/tutorial-web-app-operator/pull/33

**Comment by maleck13** [comment]
Same as webapp operator we need to ensure new releases of this are cut appropriately and the update made to the installer. But otherwise good with this change

**Comment by maleck13** [comment]
@tremes We need to update the release process for the operator. It should match the way we do it for the installer. IE create a branch update the image to the release version commit and push then create a tag

**Pull request merged**
